{% set version = '1.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-medicalrisk
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/medicalrisk_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/medicalrisk/medicalrisk_{{ version }}.tar.gz
  sha256: 40d6a461b16806be6b6cd3f5986e44a9800b152340c7f3bb54125e6abcace38a

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-hash
    - r-plyr >=1.5
    - r-reshape2
  run:
    - r-base
    - r-hash
    - r-plyr >=1.5
    - r-reshape2

test:
  commands:
    - $R -e "library('medicalrisk')"           # [not win]
    - "\"%R%\" -e \"library('medicalrisk')\""  # [win]

about:
  home: https://github.com/patrickmdnet/medicalrisk
  license: GPL-3
  summary: Generates risk estimates and comorbidity flags from ICD-9-CM codes available in administrative
    medical datasets. The package supports the Charlson Comorbidity Index, the Elixhauser
    Comorbidity classification, the Revised Cardiac Risk Index, and the Risk Stratification
    Index.  Methods are table-based, fast, and use the 'plyr' package, so parallelization
    is possible for large jobs. Also includes a sample of real ICD-9 data for 100 patients
    from a publicly available dataset.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: medicalrisk
# Type: Package
# Title: Medical Risk and Comorbidity Tools for ICD-9-CM Data
# Version: 1.3
# Date: 2020-02-28
# Authors@R: c(person("Patrick", "McCormick", role = c("aut", "cre"), email = "patrick.mccormick@alum.mit.edu"), person("Thomas", "Joseph", role = "aut", email = "thomas.joseph@mountsinai.org"))
# Description: Generates risk estimates and comorbidity flags from ICD-9-CM codes available in administrative medical datasets. The package supports the Charlson Comorbidity Index, the Elixhauser Comorbidity classification, the Revised Cardiac Risk Index, and the Risk Stratification Index.  Methods are table-based, fast, and use the 'plyr' package, so parallelization is possible for large jobs. Also includes a sample of real ICD-9 data for 100 patients from a publicly available dataset.
# Depends: R (>= 3.0.0)
# Imports: plyr (>= 1.5), reshape2, hash
# Suggests: testthat, knitr, ggplot2, gridExtra
# License: GPL-3 | file LICENSE
# LazyData: true
# VignetteBuilder: knitr
# RoxygenNote: 7.0.2
# Encoding: UTF-8
# BugReports: https://github.com/patrickmdnet/medicalrisk/issues
# URL: https://github.com/patrickmdnet/medicalrisk
# NeedsCompilation: no
# Packaged: 2020-02-29 04:04:46 UTC; patri
# Author: Patrick McCormick [aut, cre], Thomas Joseph [aut]
# Maintainer: Patrick McCormick <patrick.mccormick@alum.mit.edu>
# Repository: CRAN
# Date/Publication: 2020-02-29 21:00:02 UTC
