travis:
  secure:
    BINSTAR_TOKEN: KwkEl7LlH8sMPxLfkdtHlhYmxeH9tZrZ4+3cQC2dI98Sc9Ma5hDyj2KvxSc1GJlw3+mztbV4i8edvxazKCqB+D3OaHgkcAV8GxJRq7IP5qdi3xOBzxYtse2Cy5BzddDS8M1gm02/xT2tRB3MTuFTGGkT7C5VtzrRhkJ7wBb6/hNb5AYCmMwo4f64Okl92jl9E6gFIK3g+FIMgatCCwanMFVptuVHkm8DXhqHUbiseO0yLaRiIGPOTnWbf/Vz170E4wrgJ1ukJxc4J9RtVI9KTgxkiR8jHYSQnIZXK0Ip7rY4wNnUSli54JiOWzTE6fgS5rU/UatVMMf+J3bQEhxOw6O6jJvNzQKWCCmiw5OEk7k3CfOlD996OK5E6Cn3QvrBuxmvkKM57YpqYGaZxmlrru7VOOUpkGvNIpAJUiK3SsoW3pBp26eWjFI7eIs6rY2t62E4J8jhH0rNdw4PHYv/z5IACz8dL6Il8R8aZwu0hwKymmP0hlUE2mFidQAAOSSYH8chfUNWnugxAyJx2Z1DpvEIC22utiaW8eajKT+ndWht8rMiQFYsJKrHB3B9zbXtFHI2//xTWSVsJSLiHbjd9qUNOhvxBim7YNL+lS//k3x2HokaR2S/30RflHFyKXYbpCRZMaxOGZDpRmXDPJve66pkVgrQB3gkzFyT+jwQZoM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
